# commands run on 2023/11/17
jbrowse add-track https://raw.githubusercontent.com/oist/Oikopleuradioica_genomeannotation/main/Bar2_p4/v1.1/Bar2_p4_5primeutr_v1.1.gtf -a Bar2_p4 -n Bar2_p4_5primeutr_v1.1.gtf -d "v1 with UTRs inferred from CAGE peaks"
jbrowse add-track https://raw.githubusercontent.com/oist/Oikopleuradioica_genomeannotation/main/OKI.I69/v2.1/OKI2018_I69_5primeutr_v2.1.gtf -a OKI.I69 -n OKI2018_I69_5primeutr_v2.1.gtf -d "v2 with UTRs inferred from CAGE peaks"
jbrowse add-track https://raw.githubusercontent.com/oist/Oikopleuradioica_genomeannotation/main/OSKA2016v1.9/v2.1/OSKA2016_5primeutr_v2.1.gtf -a OSKA2016v1.9 -n OSKA2016_5primeutr_v2.1.gtf -d "v2 with UTRs inferred from CAGE peaks"
jbrowse add-track https://raw.githubusercontent.com/oist/Oikopleuradioica_genomeannotation/main/Bar2_p4/v4/Bar2_p4_5primeutr_v4.0.gtf -a Bar2_p4 -n Bar2_p4_5primeutr_v4.0.gtf -d "v4 with UTRs inferred from CAGE peaks"

# commands run on 2023/11/29
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2021-12-17_Okinawa_Oik/CrossAlignments/consensus_clusters_no_OKItoOKI.bed -a OKI.I69 -n "Consensus promoter CAGE peaks" -d "Consensus promoter CAGE peaks" --category "CAGE peaks" --force
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2021-12-17_Okinawa_Oik/CrossAlignments/consensus_clusters_sl_OKItoOKI.bed -a OKI.I69 -n "Consensus trans-splicing CAGE peaks" -d "Consensus trans-splicing CAGE peaks" --category "CAGE peaks" --force
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2022-11-09_Barcelona_Oik/CrossAlignments/consensus_clusters_no_BARtoBAR.bed -a Bar2_p4 -n "Consensus promoter CAGE peaks" -d "Consensus promoter CAGE peaks" --category "CAGE peaks" --force
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2022-11-09_Barcelona_Oik/CrossAlignments/consensus_clusters_sl_BARtoBAR.bed -a Bar2_p4 -n "Consensus trans-splicing CAGE peaks" -d "Consensus trans-splicing CAGE peaks" --category "CAGE peaks" --force
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2022-02-09_Osaka_Oik/CrossAlignments/consensus_clusters_no_OSAtoOSA.bed -a OSKA2016v1.9 -n "Consensus promoter CAGE peaks" -d "Consensus promoter CAGE peaks" --category "CAGE peaks" --force
jbrowse add-track https://raw.githubusercontent.com/oist/LuscombeU-CAGE_libraries/main/2022-02-09_Osaka_Oik/CrossAlignments/consensus_clusters_sl_OSAtoOSA.bed -a OSKA2016v1.9 -n "Consensus trans-splicing CAGE peaks" -d "Consensus trans-splicing CAGE peaks" --category "CAGE peaks" --force